### ISSUE TITLE
No items of type PR found.

### ISSUE THREAD

**Issue by OBOTService** [ArasLabs/Sample-AngularJs-PR-management#1]
I'm try using url http://xxxx/OBOTSP12/Server/odata/PR get json data, but it's show error
 "error": {
        "code": "NotFound",
        "message": "No items of type PR found."
    }
}
could you tell me why?

**Comment by EliJDonahue** [comment]
Try checking the following:
* Confirm that there are PR items in the database you're querying.
* Confirm that the user you're using to send the query has permission to get PR items.

**Comment by chithsuheinn29** [comment]
I can log in only admin and root user.I'm finding that which codes are used for authentication.Please, help me.

**Comment by EliJDonahue** [comment]
Hi @chithsuheinn29, can you file a separate issue for this behavior? It sounds like the issue you're seeing is unrelated to this thread.

**Comment by chithsuheinn29** [comment]
// API interceptor to handle user connexion
    .service('APIIntervceptor', function (userLocal, $rootScope) {
        var service = this;
        service.request = (config) => {

            var currentUser = userLocal.getCredentials()
            if (currentUser) {
                config.headers.DATABASE = currentUser.db
                config.headers.AUTHUSER = currentUser.login
                config.headers.AUTHPASSWORD = currentUser.password
            }
            return config
        }
        service.responseError = (response) => {
            if (response.status === 401) {
                $rootScope.$broadcast('unauthorized')
            }
            return response
        }
    })

    // plug the API interceptor
    .config(function ($httpProvider) {
        $httpProvider.interceptors.push('APIIntervceptor')
    })

Sir, i would like to know about above code is joining the database of aras or not?
and i know databasename , login and password get from userconfig.js.but ,i don't known clearly whether service.request function work to join with aras or not.please,help me.

**Comment by chithsuheinn29** [comment]
Sir, I would like to use to react instead of angular. Now,i'm trying to set up react in IIS.I can't see my app.
I only see the folder. Please, help me.
![pic](https://user-images.githubusercontent.com/40754988/58953075-70a4e680-87bb-11e9-8fb6-f8f216316e21.png)

**Comment by EliJDonahue** [comment]
Hi @chithsuheinn29, it sounds like you're running into a React and/or IIS issue that is unrelated to this thread. I recommend checking out a React user forum or setup tutorial. I'm guessing the problem may be that your physical directory doesn't have an index.html file, but I'm not familiar with React so I can't say for sure.

**Comment by EliJDonahue** [comment]
I'm closing out this issue, as it's been open for a year with no feedback from the original poster or confirmation from other users. We'll reopen the issue if someone else can reproduce it.
